service: financial-health
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  home:
    handler: handler.home
    events:
      - httpApi:
          path: /
          method: get
  
  login:
    handler: app/modules/user/index.login
    events:
      - httpApi:
          path: /login
          method: post
  
  register:
    handler: app/modules/user/index.register
    events:
      - httpApi:
          path: /register
          method: post

          
  jwt-auth:
    handler: app/modules/authorizer/index.jwtCheck

plugins:
  - serverless-offline
  - serverless-dotenv-plugin



# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
